In [26]:
from call_goldenrecord import main as M
import pandas as pd

In [27]:
input_file = "../data/mitdwh/"
output_file = "./tmp.csv"

In [28]:
df = pd.read_csv(input_file + "union_table.csv", encoding='latin1')

In [29]:
df[0:15]

,sis department name,building key,mit id,full name,office location,cluster_id
0,linguistics and philosophy,32.0,900041301,"degraff, michel anne-frederic",32d-826,900041301degraff
1,linguistics and philosophy,32.0,995653880,"sukha, jim",32-g785,995653880sukhaj
2,linguistics and philosophy,32.0,921917020,"albright, adam",32d-830,921917020albright
3,linguistics and philosophy,32.0,980373354,"hackl, martin",32d-966,980373354hackl
4,linguistics and philosophy,32.0,925833144,"aranov-zucker, elisheva",32d-d-464,925833144earanov
5,linguistics and philosophy,32.0,900029885,"flemming, edward",32d-858,900029885flemming
6,linguistics and philosophy,32.0,917375854,"rosenstein, elizabeth gwynne",32d-958,917375854leaena
7,linguistics and philosophy,32.0,900008630,"von fintel, kai",32d-884,900008630fintel
8,linguistics and philosophy,32.0,924312439,"skow, bradford",32d-930,924312439bskow
9,linguistics and philosophy,32.0,900046696,"ketterle, glenn",32d-836a,900046696glennk
10,linguistics and philosophy,32.0,900048788,"richards, norvin w",32d-868,900048788norvin
11,linguistics and philosophy,32.0,900051465,"graham, christine s",32d-808,900051465cgraham
12,linguistics and philosophy,32.0,900027527,"sikorski, matthew m",32d-808,900027527mattski
13,linguistics and philosophy,32.0,926031392,"rochford, damien joseph",32d-808,926031392djr
14,linguistics and philosophy,32.0,913395540,"skibra, daniel",32d-808,913395540dskibra

In [30]:
M(input_file, output_file)

looking for rules for table union_table.csv at column 0
number of clusters 18050
avg size 1.45036
column: sis department name
option: 0 (default): skip,
1: replacing rule only,
2: replacing rules + full rules,
3: replacing rules + deletion rules,
4: replacing rules + deletion rules + full rules,
5: full rules only

0
looking for rules for table union_table.csv at column 1
number of clusters 18050
avg size 1.45036
column: building key
option: 0 (default): skip,
1: replacing rule only,
2: replacing rules + full rules,
3: replacing rules + deletion rules,
4: replacing rules + deletion rules + full rules,
5: full rules only

0
looking for rules for table union_table.csv at column 2
number of clusters 18050
avg size 1.45036
column: mit id
option: 0 (default): skip,
1: replacing rule only,
2: replacing rules + full rules,
3: replacing rules + deletion rules,
4: replacing rules + deletion rules + full rules,
5: full rules only

0
looking for rules for table union_table.csv at column 3
number of clusters 18050
avg size 1.45036
column: full name
option: 0 (default): skip,
1: replacing rule only,
2: replacing rules + full rules,
3: replacing rules + deletion rules,
4: replacing rules + deletion rules + full rules,
5: full rules only

0
looking for rules for table union_table.csv at column 4
number of clusters 18050
avg size 1.45036
column: office location
option: 0 (default): skip,
1: replacing rule only,
2: replacing rules + full rules,
3: replacing rules + deletion rules,
4: replacing rules + deletion rules + full rules,
5: full rules only

1
Number of Rules Generated: 67
Number of Rules In Use: 46
Number of Groups: 4



group: ------
[$$, 1, Start_Token, 1] --- [$$, 2, Alphanums, 1]
[$$, -1, Alphanums, 0] --- [$$, 1, End_Token, 0]
[$^END_T^$, -1, Very_Special_for_Path, 0] --- [$^END_T^$, -1, Very_Special_for_Path, 1]


0: |32-g-528|-->|32-g528| x5
3: |32-g-532|-->|32-g532| x2
4: |32-g-530|-->|32-g530| x2
5: |32-g-418|-->|32-g418| x2
6: |32-g-518|-->|32-g518| x1
7: |32-g-714|-->|32-g714| x1
8: |32-g-580|-->|32-g580| x1
12: |32-g-506|-->|32-g506| x1
15: |32-g-692|-->|32-g692| x1
16: |32-g-538|-->|32-g538| x1
17: |32-g-424|-->|32-g424| x1
18: |32-g-522|-->|32-g522| x1
20: |32-g-918|-->|32-g918| x1
22: |32-g-822|-->|32-g822| x1
23: |32-g-716|-->|32-g716| x1
24: |32-g-920|-->|32-g920| x1
26: |32-g-628|-->|32-g628| x1
27: |32-g-888|-->|32-g888| x1
28: |32-g-526|-->|32-g526| x1
29: |32-g-696|-->|32-g696| x1
32: |32-g-708|-->|32-g708| x1
33: |32-g-514|-->|32-g514| x1
34: |32-g-494|-->|32-g494| x1
36: |32-g-504|-->|32-g504| x1
38: |32-g-826|-->|32-g826| x1
39: |32-g-942|-->|32-g942| x1
40: |32-g-670|-->|32-g670| x1
41: |32-g-742|-->|32-g742| x1
42: |32-g-520|-->|32-g520| x1
44: |32-g-890|-->|32-g890| x1
45: |32-g-804|-->|32-g804| x1
Sample Applications:
32-g528 --- 32-g-528
32-g532 --- 32-g-532
32-g530 --- 32-g-530
32-g418 --- 32-g-418
32-g518 --- 32-g-518
32-g714 --- 32-g-714
32-g580 --- 32-g-580
32-g506 --- 32-g-506
32-g692 --- 32-g-692
32-g538 --- 32-g-538

number of rules in this group: 31
max count: 38
------------

0: do not apply all of them;  1: apply them to all;  2: apply them reversely; 3: postpone;  4; exit

1
After applying 0 groups:
1[11152], 2[6858], 3[40],
number of duplicates: 40



group: ------
[$$, 1, Start_Token, 1] --- [$$, 2, Alphabets, 0]
[$^END_T^$, -1, Very_Special_for_Path, 0] --- [$^END_T^$, -1, Very_Special_for_Path, 1]


2: |ne47-5th floor|-->|ne47-5| x2
10: |ne25-7th floor|-->|ne25-7| x1
11: |e38-5th floor|-->|e38-5| x1
14: |e90-9th floor|-->|e90-9| x1
19: |e70-12th floor|-->|e70-12| x1
31: |e40-2nd floor|-->|e40-2| x1
43: |ne47-4th floor|-->|ne47-4| x1
Sample Applications:
ne47-5th floor --- ne47-5
ne25-7th floor --- ne25-7
e38-5th floor --- e38-5
e90-9th floor --- e90-9
e70-12th floor --- e70-12
e40-2nd floor --- e40-2
ne47-4th floor --- ne47-4

number of rules in this group: 7
max count: 8
------------

0: do not apply all of them;  1: apply them to all;  2: apply them reversely; 3: postpone;  4; exit

1
After applying 1 groups:
1[11152], 2[6866], 3[32],
number of duplicates: 32



group: ------
[$$, 1, Start_Token, 1] --- [$$, 1, Alphanums, 1]
[$$, 2, Alphanums, 0] --- [$$, 1, End_Token, 0]
[$^END_T^$, -1, Very_Special_for_Path, 0] --- [$^END_T^$, -1, Very_Special_for_Path, 1]


9: |32-d-678|-->|32d-678| x1
13: |32-d-458|-->|32d-458| x1
21: |32-d-770|-->|32d-770| x1
30: |32-d-640|-->|32d-640| x1
35: |32-d-784|-->|32d-784| x1
Sample Applications:
32d-678 --- 32-d-678
32d-458 --- 32-d-458
32d-770 --- 32-d-770
32d-640 --- 32-d-640
32d-784 --- 32-d-784

number of rules in this group: 5
max count: 5
------------

0: do not apply all of them;  1: apply them to all;  2: apply them reversely; 3: postpone;  4; exit

1
After applying 2 groups:
1[11152], 2[6871], 3[27],
number of duplicates: 27



group: ------
[$$, 1, Start_Token, 1] --- [$$, -2, Alphanums, 0]
[$$, -1, Alphanums, 0] --- [$$, 1, End_Token, 0]
[$^END_T^$, -1, Very_Special_for_Path, 0] --- [$^END_T^$, -1, Very_Special_for_Path, 1]


1: |ll-millstone-ms-27|-->|ll-millstone-27| x3
25: |ll-millstone-ms-115|-->|ll-millstone-115| x1
37: |ll-millstone-ms-35|-->|ll-millstone-35| x1
Sample Applications:
ll-millstone-ms-27 --- ll-millstone-27
ll-millstone-ms-115 --- ll-millstone-115
ll-millstone-ms-35 --- ll-millstone-35

number of rules in this group: 3
max count: 5
------------

0: do not apply all of them;  1: apply them to all;  2: apply them reversely; 3: postpone;  4; exit

1
After applying 3 groups:
1[11152], 2[6876], 3[22],
number of duplicates: 22



Done with current column

Successfully Exit!

In [31]:
df = pd.read_csv("/Users/ra-mit/development/civilizer_demo/civilizer_services/grecord_service/code/tmp.csv", encoding='latin1')

In [32]:
df[1:5]

,sis department name,building key,mit id,full name,office location,cluster_id
1,linguistics and philosophy,32.0,995653880,"sukha, jim",32g-785,995653880sukhaj
2,linguistics and philosophy,32.0,921917020,"albright, adam",32d-830,921917020albright
3,linguistics and philosophy,32.0,980373354,"hackl, martin",32d-966,980373354hackl
4,linguistics and philosophy,32.0,925833144,"aranov-zucker, elisheva",32d-464,925833144earanov